///////////////////////////////////////////////////////////
//  eLogErrorType.cs
//  Implementation of the Enumeration eLogErrorType
//  Generated by Enterprise Architect
//  Created on:      13-9ÔÂ-2016 22:41:25
//  Original author: dazhuangtage
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
namespace SYC.Log4
{
    public enum eLogErrorType : int
    {

        Commonly,
        Warning,
        Information,
        Error

    }//end eLogErrorType

}//end namespace ÓòÄ£ÐÍ