///////////////////////////////////////////////////////////
//  LogModel.cs
//  Implementation of the Class LogModel
//  Generated by Enterprise Architect
//  Created on:      13-9月-2016 22:32:43
//  Original author: dazhuangtage
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace SYC.Log4
{
    /// <summary>
    /// 日志域类实体模型
    /// </summary>
    public class LogModel
    {

        /// <summary>
        /// 自定义错误编码
        /// </summary>
        public string Code;
        /// <summary>
        /// 错误级别
        /// </summary>
        public eLogErrorType ErrorType;
        /// <summary>
        /// 异常类型
        /// </summary>
        public Exception Exexceptions;
        /// <summary>
        /// 是否只在Debug模式下记录
        /// </summary>
        public bool IsDebug;
        /// <summary>
        /// 是否发送消息
        /// </summary>
        public bool IsSendMessage;
        /// <summary>
        /// 处理过后的错误消息
        /// </summary>
        public string Message;

    }//end LogModel

}//end namespace 域模型