///////////////////////////////////////////////////////////
//  EventLogProvider.cs
//  Implementation of the Class EventLogProvider
//  Generated by Enterprise Architect
//  Created on:      13-9月-2016 22:36:23
//  Original author: dazhuangtage
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
namespace SYC.Log4
{
	/// <summary>
	/// 持久化到文件
	/// </summary>
	public class EventLogProvider : ILogProvider {

		public EventLogProvider(){

		}

		~EventLogProvider(){

		}

		/// 
		/// <param name="logModel"></param>
		public void Write(LogModel logModel){

		}

	}//end EventLogProvider

}//end namespace 默认日志提供程序