///////////////////////////////////////////////////////////
//  FileLogProvider.cs
//  Implementation of the Class FileLogProvider
//  Generated by Enterprise Architect
//  Created on:      13-9月-2016 22:35:36
//  Original author: dazhuangtage
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
namespace SYC.Log4
{
	/// <summary>
	/// 持久化到文件
	/// </summary>
	public class FileLogProvider : ILogProvider {

		private string FileName;
		public string FilePath;
		public int FileSize;

		public FileLogProvider(){

		}

		~FileLogProvider(){

		}

		/// 
		/// <param name="logModel"></param>
		public void Write(LogModel logModel){

		}

	}//end FileLogProvider

}//end namespace 默认日志提供程序