///////////////////////////////////////////////////////////
//  MemoryQueueProvider.cs
//  Implementation of the Class MemoryQueueProvider
//  Generated by Enterprise Architect
//  Created on:      13-9月-2016 22:37:07
//  Original author: dazhuangtage
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
namespace SYC.Log4
{
	/// <summary>
	/// 内存消息队列提供程序
	/// </summary>
	public class MemoryQueueProvider : IQueueProvider {

		public MemoryQueueProvider(){

		}


		public LogModel Get(){

			return null;
		}

		/// 
		/// <param name="model"></param>
		public void Set(LogModel model){

		}

	}//end MemoryQueueProvider

}//end namespace 默认队列提供程序