///////////////////////////////////////////////////////////
//  NosqlLogProvider.cs
//  Implementation of the Class NosqlLogProvider
//  Generated by Enterprise Architect
//  Created on:      13-9月-2016 22:36:48
//  Original author: dazhuangtage
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
namespace SYC.Log4
{
	/// <summary>
	/// 持久化到Nosql
	/// </summary>
	public class NosqlLogProvider : IQueueProvider {

		public NosqlLogProvider(){

		}

		public LogModel Get(){

			return null;
		}

		/// 
		/// <param name="model"></param>
		public void Set(LogModel model){

		}

		public void StartListen(){

		}

		/// 
		/// <param name="logModel"></param>
		public void Write(LogModel logModel){

		}

	}//end NosqlLogProvider

}//end namespace 默认队列提供程序