///////////////////////////////////////////////////////////
//  ILogProviderBuild.cs
//  Implementation of the Interface ILogProviderBuild
//  Generated by Enterprise Architect
//  Created on:      13-9月-2016 22:32:54
//  Original author: dazhuangtage
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
namespace SYC.Log4
{
	/// <summary>
	/// 日志实现类工厂
	/// </summary>
	public interface ILogProviderBuild  {

		/// 
		/// <param name="obj"></param>
		ILogProvider CreateLogProvider(object obj);
	}//end ILogProviderBuild

}//end namespace 域模型