///////////////////////////////////////////////////////////
//  INoticeable.cs
//  Implementation of the Interface INoticeable
//  Generated by Enterprise Architect
//  Created on:      13-9月-2016 22:34:45
//  Original author: dazhuangtage
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
namespace SYC.Log4
{
	/// <summary>
	/// 消息发送接口
	/// </summary>
	public interface INoticeable  {

		/// 
		/// <param name="log"></param>
		void Send(LogModel log);
	}//end INoticeable

}//end namespace 域模型