///////////////////////////////////////////////////////////
//  IQueueProviderBulid.cs
//  Implementation of the Interface IQueueProviderBulid
//  Generated by Enterprise Architect
//  Created on:      13-9ÔÂ-2016 22:34:38
//  Original author: dazhuangtage
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
namespace SYC.Log4
{
	public interface IQueueProviderBulid  {

		/// 
		/// <param name="obj"></param>
		IQueueProvider CreateQueueProvider(object obj);
	}//end IQueueProviderBulid

}//end namespace ÓòÄ£ÐÍ