///////////////////////////////////////////////////////////
//  IQueueProvider.cs
//  Implementation of the Interface IQueueProvider
//  Generated by Enterprise Architect
//  Created on:      13-9月-2016 22:36:31
//  Original author: dazhuangtage
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
namespace SYC.Log4
{
	/// <summary>
	/// 消息队列
	/// </summary>
	public interface IQueueProvider  {

	  	LogModel Get();

		/// 
		/// <param name="model"></param>
	void	Set(LogModel model);
	}//end IQueueProvider

}//end namespace 域模型